In [8]:
import pandas as pd

df = pd.read_csv(csv_path)

print("Dataset loaded successfully!")
print("Number of cases:", len(df))

df.head()

Dataset loaded successfully!
Number of cases: 80

  case_id                                               text
0    C001  Ravi Kumar contacted Suresh Rao using phone 90...
1    C002  Anil Sharma called Ravi Kumar using phone 9000...
2    C003  Priya Reddy contacted Anil Sharma using phone ...
3    C004  Suresh Rao met Priya Reddy near Tarnaka. Sures...
4    C005  Rahul Verma contacted Priya Reddy using phone ...

In [9]:
print(df["text"].iloc[0])

Ravi Kumar contacted Suresh Rao using phone 9000000001 near Secunderabad. Ravi owns a white Swift and works at Alpha Logistics. Suresh uses phone 9000000002.

In [10]:
import spacy

print("spaCy version:", spacy.__version__)

spaCy version: 3.8.16

In [11]:
import spacy

nlp = spacy.load("en_core_web_sm")

print("NLP model loaded successfully!")

NLP model loaded successfully!

In [12]:
doc = nlp(df["text"].iloc[0])

for ent in doc.ents:
    print(ent.text, "→", ent.label_)

Ravi Kumar → PERSON
Suresh Rao → PERSON
9000000001 → DATE
Secunderabad → GPE
Ravi → PERSON
Swift → PRODUCT
Alpha Logistics → ORG
9000000002 → DATE

In [13]:
import re

text = df["text"].iloc[0]

phones = re.findall(r"\b\d{10}\b", text)
accounts = re.findall(r"\b\d{12}\b", text)

print("Phones:", phones)
print("Bank Accounts:", accounts)

Phones: ['9000000001', '9000000002']
Bank Accounts: []

In [14]:
all_phones = set()
all_accounts = set()

for text in df["text"]:
    all_phones.update(re.findall(r"\b\d{10}\b", text))
    all_accounts.update(re.findall(r"\b\d{12}\b", text))

print("Unique phones:", len(all_phones))
print("Unique bank accounts:", len(all_accounts))

print("Phones:", sorted(all_phones))
print("Bank accounts:", sorted(all_accounts))

Unique phones: 15
Unique bank accounts: 8
Phones: ['9000000001', '9000000002', '9000000003', '9000000004', '9000000005', '9000000006', '9000000007', '9000000008', '9000000009', '9000000010', '9000000011', '9000000012', '9000000013', '9000000014', '9000000015']
Bank accounts: ['100000000001', '100000000002', '100000000003', '100000000004', '100000000005', '100000000006', '100000000007', '100000000008']

In [15]:
people = set()

for text in df["text"]:
    doc = nlp(text)
    for ent in doc.ents:
        if ent.label_ == "PERSON":
            people.add(ent.text)

print("Unique people:", len(people))
print(sorted(people))

Unique people: 40
['Aditya', 'Aditya Rao', 'Anil', 'Anil Sharma', 'Arjun', 'Arjun Mehta', 'Asha', 'Asha Nair', 'Divya', 'Divya Reddy', 'Harish Patel', 'Himayatnagar', 'Jubilee Hills', 'Kavya', 'Kavya Sharma', 'Kiran', 'Kiran Reddy', 'Kumar', 'Lakshmi Rao', 'Manoj Kumar', 'Maruti Baleno', 'Maruti Swift', 'Meena Patel', 'Neha', 'Neha Singh', 'Nikhil', 'Nikhil Kumar', 'Pooja Sharma', 'Priya Reddy', 'Rahul Verma', 'Ravi', 'Ravi Kumar', 'Rohit Gupta', 'Sanjay Verma', 'Sneha Rao', 'Suresh Rao', 'Swati Verma', 'Tata Nexon', 'Varun Reddy', 'Vikram Singh']

In [16]:
canonical_people = [
    "Ravi Kumar",
    "Suresh Rao",
    "Anil Sharma",
    "Priya Reddy",
    "Rahul Verma",
    "Neha Singh",
    "Arjun Mehta",
    "Kiran Reddy",
    "Sneha Rao",
    "Vikram Singh",
    "Meena Patel",
    "Aditya Rao",
    "Pooja Sharma",
    "Manoj Kumar",
    "Divya Reddy",
    "Sanjay Verma",
    "Asha Nair",
    "Rohit Gupta",
    "Lakshmi Rao",
    "Varun Reddy",
    "Kavya Sharma",
    "Nikhil Kumar",
    "Swati Verma",
    "Harish Patel"
]

print("Canonical people:", len(canonical_people))
print(canonical_people)

Canonical people: 24
['Ravi Kumar', 'Suresh Rao', 'Anil Sharma', 'Priya Reddy', 'Rahul Verma', 'Neha Singh', 'Arjun Mehta', 'Kiran Reddy', 'Sneha Rao', 'Vikram Singh', 'Meena Patel', 'Aditya Rao', 'Pooja Sharma', 'Manoj Kumar', 'Divya Reddy', 'Sanjay Verma', 'Asha Nair', 'Rohit Gupta', 'Lakshmi Rao', 'Varun Reddy', 'Kavya Sharma', 'Nikhil Kumar', 'Swati Verma', 'Harish Patel']

In [17]:
people_found = set()

for text in df["text"]:
    for person in canonical_people:
        if person in text:
            people_found.add(person)

print("People found:", len(people_found))
print(sorted(people_found))

People found: 24
['Aditya Rao', 'Anil Sharma', 'Arjun Mehta', 'Asha Nair', 'Divya Reddy', 'Harish Patel', 'Kavya Sharma', 'Kiran Reddy', 'Lakshmi Rao', 'Manoj Kumar', 'Meena Patel', 'Neha Singh', 'Nikhil Kumar', 'Pooja Sharma', 'Priya Reddy', 'Rahul Verma', 'Ravi Kumar', 'Rohit Gupta', 'Sanjay Verma', 'Sneha Rao', 'Suresh Rao', 'Swati Verma', 'Varun Reddy', 'Vikram Singh']

In [18]:
entities = []

for case_id, text in zip(df["case_id"], df["text"]):

    # People
    for person in canonical_people:
        if person in text:
            entities.append({
                "case_id": case_id,
                "entity_type": "PERSON",
                "entity_value": person
            })

    # Phones
    for phone in re.findall(r"\b\d{10}\b", text):
        entities.append({
            "case_id": case_id,
            "entity_type": "PHONE",
            "entity_value": phone
        })

    # Bank accounts
    for account in re.findall(r"\b\d{12}\b", text):
        entities.append({
            "case_id": case_id,
            "entity_type": "BANK_ACCOUNT",
            "entity_value": account
        })

entities_df = pd.DataFrame(entities)

print("Total entity mentions:", len(entities_df))
entities_df.head(10)

Total entity mentions: 229

  case_id   entity_type  entity_value
0    C001        PERSON    Ravi Kumar
1    C001        PERSON    Suresh Rao
2    C001         PHONE    9000000001
3    C001         PHONE    9000000002
4    C002        PERSON    Ravi Kumar
5    C002        PERSON   Anil Sharma
6    C002         PHONE    9000000003
7    C002  BANK_ACCOUNT  100000000001
8    C003        PERSON   Anil Sharma
9    C003        PERSON   Priya Reddy

In [19]:
print("Unique entities by type:")
print(entities_df.groupby("entity_type")["entity_value"].nunique())

Unique entities by type:
entity_type
BANK_ACCOUNT     8
PERSON          24
PHONE           15
Name: entity_value, dtype: int64

In [20]:
organizations = [
    "Alpha Logistics",
    "Beta Technologies",
    "Gamma Transport",
    "Delta Services",
    "Epsilon Finance"
]

orgs_found = set()

for text in df["text"]:
    for org in organizations:
        if org in text:
            orgs_found.add(org)

print("Unique organizations:", len(orgs_found))
print(sorted(orgs_found))

Unique organizations: 5
['Alpha Logistics', 'Beta Technologies', 'Delta Services', 'Epsilon Finance', 'Gamma Transport']

In [21]:
for case_id, text in zip(df["case_id"], df["text"]):

    for org in organizations:
        if org in text:
            entities.append({
                "case_id": case_id,
                "entity_type": "ORGANIZATION",
                "entity_value": org
            })

entities_df = pd.DataFrame(entities)

print("Total entity mentions:", len(entities_df))

Total entity mentions: 260

In [22]:
print("Unique entities by type:")
print(entities_df.groupby("entity_type")["entity_value"].nunique())

Unique entities by type:
entity_type
BANK_ACCOUNT     8
ORGANIZATION     5
PERSON          24
PHONE           15
Name: entity_value, dtype: int64

In [23]:
locations = set()

for text in df["text"]:
    doc = nlp(text)

    for ent in doc.ents:
        if ent.label_ in ["GPE", "LOC"]:
            locations.add(ent.text)

print("Unique locations found:", len(locations))
print(sorted(locations))

Unique locations found: 23
['Abids', 'Ameerpet', 'Banjara Hills', 'Begumpet', 'Boduppal', 'Dilsukhnagar', 'Habsiguda', 'Himayatnagar', 'Honda City', 'Jubilee Hills', 'Koti', 'Kukatpally', 'Malkajgiri', 'Mehdipatnam', 'Nacharam', 'Nagole', 'Nallakunta', 'Pocharam', 'Pooja', 'Pooja Sharma', 'Saroornagar', 'Secunderabad', 'Swati']

In [24]:
false_locations = {"Honda City", "Pooja", "Pooja Sharma", "Swati"}

clean_locations = sorted(locations - false_locations)

print("Actual locations:", len(clean_locations))
print(clean_locations)

Actual locations: 19
['Abids', 'Ameerpet', 'Banjara Hills', 'Begumpet', 'Boduppal', 'Dilsukhnagar', 'Habsiguda', 'Himayatnagar', 'Jubilee Hills', 'Koti', 'Kukatpally', 'Malkajgiri', 'Mehdipatnam', 'Nacharam', 'Nagole', 'Nallakunta', 'Pocharam', 'Saroornagar', 'Secunderabad']

In [25]:
for case_id, text in zip(df["case_id"], df["text"]):

    for location in clean_locations:
        if location in text:
            entities.append({
                "case_id": case_id,
                "entity_type": "LOCATION",
                "entity_value": location
            })

entities_df = pd.DataFrame(entities)

print("Total entity mentions:", len(entities_df))

Total entity mentions: 329

In [26]:
print("Unique entities by type:")
print(entities_df.groupby("entity_type")["entity_value"].nunique())

Unique entities by type:
entity_type
BANK_ACCOUNT     8
LOCATION        19
ORGANIZATION     5
PERSON          24
PHONE           15
Name: entity_value, dtype: int64

In [27]:
vehicles = [
    "Swift",
    "Honda City",
    "Hyundai Creta",
    "Maruti Swift",
    "Tata Nexon",
    "Honda Activa",
    "Hyundai i20",
    "Maruti Baleno",
    "Tata Altroz",
    "Hyundai Venue"
]

vehicles_found = set()

for text in df["text"]:
    for vehicle in vehicles:
        if vehicle in text:
            vehicles_found.add(vehicle)

print("Unique vehicle types found:", len(vehicles_found))
print(sorted(vehicles_found))

Unique vehicle types found: 10
['Honda Activa', 'Honda City', 'Hyundai Creta', 'Hyundai Venue', 'Hyundai i20', 'Maruti Baleno', 'Maruti Swift', 'Swift', 'Tata Altroz', 'Tata Nexon']

In [28]:
for case_id, text in zip(df["case_id"], df["text"]):

    for vehicle in vehicles:
        if vehicle in text:
            entities.append({
                "case_id": case_id,
                "entity_type": "VEHICLE",
                "entity_value": vehicle
            })

entities_df = pd.DataFrame(entities)

print("Total entity mentions:", len(entities_df))

Total entity mentions: 373

In [29]:
print("Unique entities by type:")
print(entities_df.groupby("entity_type")["entity_value"].nunique())

print("\nTotal unique entities:",
      entities_df["entity_value"].nunique())

Unique entities by type:
entity_type
BANK_ACCOUNT     8
LOCATION        19
ORGANIZATION     5
PERSON          24
PHONE           15
VEHICLE         10
Name: entity_value, dtype: int64

Total unique entities: 81

In [31]:
relationships = []

for case_id, text in zip(df["case_id"], df["text"]):

    for person1 in canonical_people:
        for person2 in canonical_people:

            if person1 != person2:
                pattern = person1 + " contacted " + person2

                if pattern in text:
                    relationships.append({
                        "case_id": case_id,
                        "source": person1,
                        "relation": "CONTACTED",
                        "target": person2
                    })

relationships_df = pd.DataFrame(relationships)

print("Relationships found:", len(relationships_df))
relationships_df.head(10)

Relationships found: 42

  case_id        source   relation        target
0    C001    Ravi Kumar  CONTACTED    Suresh Rao
1    C003   Priya Reddy  CONTACTED   Anil Sharma
2    C005   Rahul Verma  CONTACTED   Priya Reddy
3    C007   Arjun Mehta  CONTACTED    Neha Singh
4    C009     Sneha Rao  CONTACTED   Kiran Reddy
5    C011   Meena Patel  CONTACTED  Vikram Singh
6    C013  Pooja Sharma  CONTACTED    Aditya Rao
7    C015   Divya Reddy  CONTACTED   Manoj Kumar
8    C017     Asha Nair  CONTACTED  Sanjay Verma
9    C019   Lakshmi Rao  CONTACTED   Rohit Gupta

In [32]:
for case_id, text in zip(df["case_id"], df["text"]):

    phones_in_text = re.findall(r"\b\d{10}\b", text)

    for phone in phones_in_text:
        for person in canonical_people:
            if person in text:
                relationships.append({
                    "case_id": case_id,
                    "source": person,
                    "relation": "USES",
                    "target": phone
                })

relationships_df = pd.DataFrame(relationships)

print("Total relationships:", len(relationships_df))
relationships_df.tail(10)

Total relationships: 132

    case_id        source relation      target
122    C044   Varun Reddy     USES  9000000011
123    C044   Swati Verma     USES  9000000011
124    C045  Kavya Sharma     USES  9000000012
125    C045  Harish Patel     USES  9000000012
126    C046    Ravi Kumar     USES  9000000013
127    C046  Nikhil Kumar     USES  9000000013
128    C047    Suresh Rao     USES  9000000014
129    C047   Swati Verma     USES  9000000014
130    C048   Priya Reddy     USES  9000000015
131    C048  Harish Patel     USES  9000000015

In [33]:
relationships = []

for case_id, text in zip(df["case_id"], df["text"]):

    # CONTACTED
    for person1 in canonical_people:
        for person2 in canonical_people:
            if person1 != person2:
                pattern = person1 + " contacted " + person2
                if pattern in text:
                    relationships.append({
                        "case_id": case_id,
                        "source": person1,
                        "relation": "CONTACTED",
                        "target": person2
                    })

    # USES PHONE
    for person in canonical_people:
        for phone in re.findall(r"\b\d{10}\b", text):
            pattern = person + " uses phone " + phone
            if pattern in text:
                relationships.append({
                    "case_id": case_id,
                    "source": person,
                    "relation": "USES",
                    "target": phone
                })

relationships_df = pd.DataFrame(relationships)

print("Total relationships:", len(relationships_df))
relationships_df.head(15)

Total relationships: 42

   case_id        source   relation        target
0     C001    Ravi Kumar  CONTACTED    Suresh Rao
1     C003   Priya Reddy  CONTACTED   Anil Sharma
2     C005   Rahul Verma  CONTACTED   Priya Reddy
3     C007   Arjun Mehta  CONTACTED    Neha Singh
4     C009     Sneha Rao  CONTACTED   Kiran Reddy
5     C011   Meena Patel  CONTACTED  Vikram Singh
6     C013  Pooja Sharma  CONTACTED    Aditya Rao
7     C015   Divya Reddy  CONTACTED   Manoj Kumar
8     C017     Asha Nair  CONTACTED  Sanjay Verma
9     C019   Lakshmi Rao  CONTACTED   Rohit Gupta
10    C021  Kavya Sharma  CONTACTED   Varun Reddy
11    C023   Swati Verma  CONTACTED  Nikhil Kumar
12    C025    Ravi Kumar  CONTACTED   Anil Sharma
13    C027   Priya Reddy  CONTACTED    Neha Singh
14    C029   Rahul Verma  CONTACTED   Kiran Reddy

In [34]:
for text in df["text"]:
    if re.search(r"\b\d{10}\b", text):
        print(text)

Ravi Kumar contacted Suresh Rao using phone 9000000001 near Secunderabad. Ravi owns a white Swift and works at Alpha Logistics. Suresh uses phone 9000000002.
Anil Sharma called Ravi Kumar using phone 9000000003 near Uppal. Anil owns a black Honda City and has bank account 100000000001.
Priya Reddy contacted Anil Sharma using phone 9000000004 near Malkajgiri. Priya owns a blue Hyundai Creta and works at Beta Technologies.
Suresh Rao met Priya Reddy near Tarnaka. Suresh used phone 9000000005 and owns a red Maruti Swift.
Rahul Verma contacted Priya Reddy using phone 9000000006 near Nacharam. Rahul owns a silver Tata Nexon and works at Gamma Transport.
Neha Singh called Rahul Verma using phone 9000000007 near Habsiguda. Neha owns a grey Honda Activa and has bank account 100000000002.
Arjun Mehta contacted Neha Singh using phone 9000000008 near Begumpet. Arjun owns a white Hyundai i20 and works at Delta Services.
Kiran Reddy met Arjun Mehta near Ameerpet. Kiran used phone 9000000009 and has bank account 100000000003.
Sneha Rao contacted Kiran Reddy using phone 9000000010 near Kukatpally. Sneha owns a black Maruti Baleno and works at Epsilon Finance.
Vikram Singh called Sneha Rao using phone 9000000011 near Banjara Hills. Vikram owns a blue Honda City and has bank account 100000000004.
Meena Patel contacted Vikram Singh using phone 9000000012 near Jubilee Hills. Meena owns a white Tata Altroz and works at Alpha Logistics.
Aditya Rao met Meena Patel near Himayatnagar. Aditya used phone 9000000013 and has bank account 100000000005.
Pooja Sharma contacted Aditya Rao using phone 9000000014 near Nallakunta. Pooja owns a red Hyundai Venue and works at Beta Technologies.
Manoj Kumar called Pooja Sharma using phone 9000000015 near Koti. Manoj owns a black Tata Nexon and has bank account 100000000006.
Asha Nair contacted Sanjay Verma using phone 9000000001 near Dilsukhnagar. Asha owns a blue Honda Activa.
Rohit Gupta called Asha Nair using phone 9000000002 near LB Nagar. Rohit owns a white Honda City and works at Epsilon Finance.
Varun Reddy met Lakshmi Rao near Nagole. Varun owns a black Hyundai Creta and uses phone 9000000003.
Kavya Sharma contacted Varun Reddy using phone 9000000004 near Boduppal. Kavya owns a red Tata Altroz and works at Beta Technologies.
Nikhil Kumar called Kavya Sharma using phone 9000000005 near Pocharam. Nikhil has bank account 100000000001 and owns a grey Maruti Baleno.
Swati Verma contacted Nikhil Kumar near Secunderabad. Swati uses phone 9000000006 and works at Gamma Transport.
Ravi Kumar contacted Anil Sharma near Malkajgiri using phone 9000000007. Ravi was seen with a white Swift.
Suresh Rao called Rahul Verma near Tarnaka using phone 9000000008. Suresh was seen with a red Maruti Swift.
Priya Reddy contacted Neha Singh near Nacharam using phone 9000000009. Priya was seen with a blue Hyundai Creta.
Anil Sharma met Arjun Mehta near Habsiguda using phone 9000000010. Anil was seen with a black Honda City.
Rahul Verma contacted Kiran Reddy near Begumpet using phone 9000000011. Rahul was seen with a silver Tata Nexon.
Neha Singh called Sneha Rao near Ameerpet using phone 9000000012. Neha was seen with a grey Honda Activa.
Arjun Mehta contacted Vikram Singh near Kukatpally using phone 9000000013. Arjun was seen with a white Hyundai i20.
Kiran Reddy met Meena Patel near Banjara Hills using phone 9000000014. Kiran was seen with a black Maruti Baleno.
Sneha Rao contacted Aditya Rao near Jubilee Hills using phone 9000000015. Sneha was seen with a black Maruti Baleno.
Vikram Singh called Pooja Sharma near Himayatnagar using phone 9000000001. Vikram was seen with a blue Honda City.
Meena Patel contacted Manoj Kumar near Nallakunta using phone 9000000002. Meena was seen with a white Tata Altroz.
Aditya Rao met Divya Reddy near Koti using phone 9000000003. Aditya was seen with a white Tata Altroz.
Pooja Sharma contacted Sanjay Verma near Abids using phone 9000000004. Pooja was seen with a red Hyundai Venue.
Manoj Kumar called Asha Nair near Mehdipatnam using phone 9000000005. Manoj was seen with a black Tata Nexon.
Divya Reddy contacted Rohit Gupta near Dilsukhnagar using phone 9000000006. Divya was seen with a silver Maruti Swift.
Sanjay Verma met Lakshmi Rao near LB Nagar using phone 9000000007. Sanjay was seen with no vehicle.
Asha Nair contacted Varun Reddy near Saroornagar using phone 9000000008. Asha was seen with a blue Honda Activa.
Rohit Gupta called Kavya Sharma near Nagole using phone 9000000009. Rohit was seen with a white Honda City.
Lakshmi Rao contacted Nikhil Kumar near Boduppal using phone 9000000010. Lakshmi was seen with no vehicle.
Varun Reddy met Swati Verma near Pocharam using phone 9000000011. Varun was seen with a black Hyundai Creta.
Kavya Sharma contacted Harish Patel near Secunderabad using phone 9000000012. Kavya was seen with a red Tata Altroz.
Nikhil Kumar called Ravi Kumar near Uppal using phone 9000000013. Nikhil was seen with a grey Maruti Baleno.
Swati Verma contacted Suresh Rao near Malkajgiri using phone 9000000014. Swati was seen with no vehicle.
Harish Patel met Priya Reddy near Tarnaka using phone 9000000015. Harish was seen with a silver Hyundai i20.

In [35]:
for case_id, text in zip(df["case_id"], df["text"]):

    for person in canonical_people:

        patterns = [
            person + " uses phone ",
            person + " used phone ",
            person + " using phone "
        ]

        for pattern in patterns:
            if pattern in text:
                start = text.index(pattern) + len(pattern)
                phone = re.match(r"\d{10}", text[start:])

                if phone:
                    relationships.append({
                        "case_id": case_id,
                        "source": person,
                        "relation": "USES",
                        "target": phone.group()
                    })

relationships_df = pd.DataFrame(relationships)

print("Total relationships:", len(relationships_df))
print("\nRelationship types:")
print(relationships_df["relation"].value_counts())

Total relationships: 57

Relationship types:
relation
CONTACTED    42
USES         15
Name: count, dtype: int64

In [36]:
relationships = []

for case_id, text in zip(df["case_id"], df["text"]):

    # CONTACTED / CALLED / MET
    for person1 in canonical_people:
        for person2 in canonical_people:
            if person1 != person2:

                for verb, relation in [
                    ("contacted", "CONTACTED"),
                    ("called", "CALLED"),
                    ("met", "MET")
                ]:
                    pattern = person1 + " " + verb + " " + person2

                    if pattern in text:
                        relationships.append({
                            "case_id": case_id,
                            "source": person1,
                            "relation": relation,
                            "target": person2
                        })

    # PERSON -> USES -> PHONE
    sentences = re.split(r"[.!?]", text)

    for sentence in sentences:
        phones = re.findall(r"\b\d{10}\b", sentence)

        if not phones:
            continue

        # Direct "uses/used phone"
        for person in canonical_people:
            if re.search(
                rf"\b{re.escape(person)}\s+(uses|used)\s+phone\s+\d{{10}}\b",
                sentence
            ):
                phone = re.search(r"\b\d{10}\b", sentence).group()

                relationships.append({
                    "case_id": case_id,
                    "source": person,
                    "relation": "USES",
                    "target": phone
                })

        # "Person contacted/called/met ... using phone"
        for person in canonical_people:
            if re.search(
                rf"^{re.escape(person)}\s+(contacted|called|met)\b.*\busing phone\s+\d{{10}}\b",
                sentence.strip()
            ):
                phone = re.search(r"\b\d{10}\b", sentence).group()

                relationships.append({
                    "case_id": case_id,
                    "source": person,
                    "relation": "USES",
                    "target": phone
                })

relationships_df = pd.DataFrame(relationships)

print("Total relationships:", len(relationships_df))
print("\nRelationship types:")
print(relationships_df["relation"].value_counts())

Total relationships: 105

Relationship types:
relation
CONTACTED    42
USES         39
CALLED       12
MET          12
Name: count, dtype: int64

In [37]:
print(relationships_df[relationships_df["relation"] == "USES"].to_string(index=False))

case_id       source relation     target
   C001   Ravi Kumar     USES 9000000001
   C002  Anil Sharma     USES 9000000003
   C003  Priya Reddy     USES 9000000004
   C005  Rahul Verma     USES 9000000006
   C006   Neha Singh     USES 9000000007
   C007  Arjun Mehta     USES 9000000008
   C009    Sneha Rao     USES 9000000010
   C010 Vikram Singh     USES 9000000011
   C011  Meena Patel     USES 9000000012
   C013 Pooja Sharma     USES 9000000014
   C014  Manoj Kumar     USES 9000000015
   C017    Asha Nair     USES 9000000001
   C018  Rohit Gupta     USES 9000000002
   C021 Kavya Sharma     USES 9000000004
   C022 Nikhil Kumar     USES 9000000005
   C025   Ravi Kumar     USES 9000000007
   C026   Suresh Rao     USES 9000000008
   C027  Priya Reddy     USES 9000000009
   C028  Anil Sharma     USES 9000000010
   C029  Rahul Verma     USES 9000000011
   C030   Neha Singh     USES 9000000012
   C031  Arjun Mehta     USES 9000000013
   C032  Kiran Reddy     USES 9000000014
   C033    Sneha Rao     USES 9000000015
   C034 Vikram Singh     USES 9000000001
   C035  Meena Patel     USES 9000000002
   C036   Aditya Rao     USES 9000000003
   C037 Pooja Sharma     USES 9000000004
   C038  Manoj Kumar     USES 9000000005
   C039  Divya Reddy     USES 9000000006
   C040 Sanjay Verma     USES 9000000007
   C041    Asha Nair     USES 9000000008
   C042  Rohit Gupta     USES 9000000009
   C043  Lakshmi Rao     USES 9000000010
   C044  Varun Reddy     USES 9000000011
   C045 Kavya Sharma     USES 9000000012
   C046 Nikhil Kumar     USES 9000000013
   C047  Swati Verma     USES 9000000014
   C048 Harish Patel     USES 9000000015

In [38]:
for case_id, text in zip(df["case_id"], df["text"]):

    for person in canonical_people:
        for vehicle in vehicles:

            pattern = person + " owns a " + vehicle

            if pattern in text:
                relationships.append({
                    "case_id": case_id,
                    "source": person,
                    "relation": "OWNS",
                    "target": vehicle
                })

relationships_df = pd.DataFrame(relationships)

print("Total relationships:", len(relationships_df))
print("\nRelationship types:")
print(relationships_df["relation"].value_counts())

Total relationships: 105

Relationship types:
relation
CONTACTED    42
USES         39
CALLED       12
MET          12
Name: count, dtype: int64

In [40]:
for case_id, text in zip(df["case_id"], df["text"]):

    for person in canonical_people:
        for vehicle in vehicles:

            pattern = person + " owns a "

            if pattern in text:
                start = text.index(pattern) + len(pattern)
                remaining_text = text[start:]

                if vehicle in remaining_text:
                    relationships.append({
                        "case_id": case_id,
                        "source": person,
                        "relation": "OWNS",
                        "target": vehicle
                    })

relationships_df = pd.DataFrame(relationships)

print("Total relationships:", len(relationships_df))

print("\nRelationship types:")
print(relationships_df["relation"].value_counts())

Total relationships: 105

Relationship types:
relation
CONTACTED    42
USES         39
CALLED       12
MET          12
Name: count, dtype: int64

In [41]:
for case_id, text in zip(df["case_id"], df["text"]):

    for person in canonical_people:

        first_name = person.split()[0]

        for vehicle in vehicles:

            pattern = first_name + " owns a "

            if pattern in text:
                start = text.index(pattern) + len(pattern)
                remaining_text = text[start:]

                if vehicle in remaining_text:
                    relationships.append({
                        "case_id": case_id,
                        "source": person,
                        "relation": "OWNS",
                        "target": vehicle
                    })

relationships_df = pd.DataFrame(relationships)

print("Total relationships:", len(relationships_df))

print("\nRelationship types:")
print(relationships_df["relation"].value_counts())

Total relationships: 123

Relationship types:
relation
CONTACTED    42
USES         39
OWNS         18
CALLED       12
MET          12
Name: count, dtype: int64

In [42]:
# Convert relationships into the team's common schema

relationship_type_map = {
    "USES": "USED",
    "OWNS": "OWNS",
    "CALLED": "CALLED",
    "CONTACTED": "ASSOCIATED_WITH",
    "MET": "ASSOCIATED_WITH"
}

final_relationships_df = relationships_df.copy()

final_relationships_df["relationship_type"] = (
    final_relationships_df["relation"]
    .map(relationship_type_map)
)

# Add relationship IDs
final_relationships_df["relationship_id"] = [
    f"R{i:03d}" for i in range(1, len(final_relationships_df) + 1)
]

# Rename columns to match team schema
final_relationships_df = final_relationships_df.rename(columns={
    "source": "source_name",
    "target": "target_name"
})

# Source record = case/report where relationship was found
final_relationships_df["source_record"] = final_relationships_df["case_id"]

# Prototype confidence
final_relationships_df["confidence"] = 0.95

# Fields not yet available from the reports
final_relationships_df["date"] = ""
final_relationships_df["properties"] = "{}"

# Keep only the final schema columns for now
final_relationships_df = final_relationships_df[
    [
        "relationship_id",
        "source_name",
        "relationship_type",
        "target_name",
        "date",
        "source_record",
        "confidence",
        "properties"
    ]
]

print("Final relationships:", len(final_relationships_df))
final_relationships_df.head(10)

Final relationships: 123

,relationship_id,source_name,relationship_type,target_name,date,source_record,confidence,properties
0,R001,Ravi Kumar,ASSOCIATED_WITH,Suresh Rao,,C001,0.95,{}
1,R002,Ravi Kumar,USED,9000000001,,C001,0.95,{}
2,R003,Anil Sharma,CALLED,Ravi Kumar,,C002,0.95,{}
3,R004,Anil Sharma,USED,9000000003,,C002,0.95,{}
4,R005,Priya Reddy,ASSOCIATED_WITH,Anil Sharma,,C003,0.95,{}
5,R006,Priya Reddy,USED,9000000004,,C003,0.95,{}
6,R007,Suresh Rao,ASSOCIATED_WITH,Priya Reddy,,C004,0.95,{}
7,R008,Rahul Verma,ASSOCIATED_WITH,Priya Reddy,,C005,0.95,{}
8,R009,Rahul Verma,USED,9000000006,,C005,0.95,{}
9,R010,Neha Singh,CALLED,Rahul Verma,,C006,0.95,{}

In [43]:
# Create final entity IDs

entity_prefix = {
    "PERSON": "P",
    "LOCATION": "L",
    "PHONE": "PH",
    "VEHICLE": "V",
    "BANK_ACCOUNT": "BA",
    "ORGANIZATION": "ORG"
}

# Get unique entities and their source records
final_entities_df = (
    entities_df
    .groupby(["entity_type", "entity_value"])["case_id"]
    .apply(lambda x: ";".join(sorted(set(x))))
    .reset_index(name="source_record")
)

# Sort entities by type and name
final_entities_df = final_entities_df.sort_values(
    ["entity_type", "entity_value"]
).reset_index(drop=True)

# Generate IDs within each entity type
final_entities_df["number"] = (
    final_entities_df.groupby("entity_type").cumcount() + 1
)

final_entities_df["entity_id"] = final_entities_df.apply(
    lambda row: f"{entity_prefix[row['entity_type']]}{row['number']:03d}",
    axis=1
)

# Final schema fields
final_entities_df["name"] = final_entities_df["entity_value"]

final_entities_df["normalized_name"] = (
    final_entities_df["name"]
    .str.lower()
    .str.strip()
)

# First-name alias for people
final_entities_df["aliases"] = final_entities_df.apply(
    lambda row: row["name"].split()[0]
    if row["entity_type"] == "PERSON"
    else "",
    axis=1
)

final_entities_df["confidence"] = 0.95
final_entities_df["properties"] = "{}"

# Arrange columns according to team schema
final_entities_df = final_entities_df[
    [
        "entity_id",
        "entity_type",
        "name",
        "normalized_name",
        "aliases",
        "source_record",
        "confidence",
        "properties"
    ]
]

print("Total unique entities:", len(final_entities_df))
print("\nEntity counts:")
print(final_entities_df["entity_type"].value_counts())

final_entities_df.head(15)

Total unique entities: 81

Entity counts:
entity_type
PERSON          24
LOCATION        19
PHONE           15
VEHICLE         10
BANK_ACCOUNT     8
ORGANIZATION     5
Name: count, dtype: int64

,entity_id,entity_type,name,normalized_name,aliases,source_record,confidence,properties
0,BA001,BANK_ACCOUNT,100000000001,100000000001,,C002;C022;C055,0.95,{}
1,BA002,BANK_ACCOUNT,100000000002,100000000002,,C006;C024;C056,0.95,{}
2,BA003,BANK_ACCOUNT,100000000003,100000000003,,C008;C049;C057,0.95,{}
3,BA004,BANK_ACCOUNT,100000000004,100000000004,,C010;C050;C058,0.95,{}
4,BA005,BANK_ACCOUNT,100000000005,100000000005,,C012;C051;C059,0.95,{}
5,BA006,BANK_ACCOUNT,100000000006,100000000006,,C014;C052;C060,0.95,{}
6,BA007,BANK_ACCOUNT,100000000007,100000000007,,C016;C053;C061,0.95,{}
7,BA008,BANK_ACCOUNT,100000000008,100000000008,,C019;C054;C062,0.95,{}
8,L001,LOCATION,Abids,abids,,C015;C037;C059,0.95,{}
9,L002,LOCATION,Ameerpet,ameerpet,,C008;C030;C052;C074,0.95,{}
10,L003,LOCATION,Banjara Hills,banjara hills,,C010;C032;C054;C076,0.95,{}
11,L004,LOCATION,Begumpet,begumpet,,C007;C029;C051;C073,0.95,{}
12,L005,LOCATION,Boduppal,boduppal,,C021;C043;C065,0.95,{}
13,L006,LOCATION,Dilsukhnagar,dilsukhnagar,,C017;C039;C061,0.95,{}
14,L007,LOCATION,Habsiguda,habsiguda,,C006;C028;C050;C072,0.95,{}

In [44]:
# Create a lookup from entity name → entity ID

entity_lookup = dict(
    zip(final_entities_df["name"], final_entities_df["entity_id"])
)

# Copy relationship table
final_relationships_with_ids = final_relationships_df.copy()

# Convert source and target names into entity IDs
final_relationships_with_ids["source_id"] = (
    final_relationships_with_ids["source_name"]
    .map(entity_lookup)
)

final_relationships_with_ids["target_id"] = (
    final_relationships_with_ids["target_name"]
    .map(entity_lookup)
)

# Arrange according to the team's final relationship schema
final_relationships_with_ids = final_relationships_with_ids[
    [
        "relationship_id",
        "source_id",
        "relationship_type",
        "target_id",
        "date",
        "source_record",
        "confidence",
        "properties"
    ]
]

print("Total relationships:", len(final_relationships_with_ids))
print("\nMissing source IDs:",
      final_relationships_with_ids["source_id"].isna().sum())

print("Missing target IDs:",
      final_relationships_with_ids["target_id"].isna().sum())

final_relationships_with_ids.head(10)

Total relationships: 123

Missing source IDs: 0
Missing target IDs: 0

,relationship_id,source_id,relationship_type,target_id,date,source_record,confidence,properties
0,R001,P017,ASSOCIATED_WITH,P021,,C001,0.95,{}
1,R002,P017,USED,PH001,,C001,0.95,{}
2,R003,P002,CALLED,P017,,C002,0.95,{}
3,R004,P002,USED,PH003,,C002,0.95,{}
4,R005,P015,ASSOCIATED_WITH,P002,,C003,0.95,{}
5,R006,P015,USED,PH004,,C003,0.95,{}
6,R007,P021,ASSOCIATED_WITH,P015,,C004,0.95,{}
7,R008,P016,ASSOCIATED_WITH,P015,,C005,0.95,{}
8,R009,P016,USED,PH006,,C005,0.95,{}
9,R010,P012,CALLED,P016,,C006,0.95,{}

In [45]:
# Validate relationship types against the team's common schema

allowed_relationships = {
    "LIVES_AT",
    "ASSOCIATED_WITH",
    "INVOLVED_IN",
    "CALLED",
    "OWNS",
    "USED",
    "LOCATED_AT",
    "REGISTERED_TO",
    "VISITED",
    "MEMBER_OF"
}

# Check for unsupported relationship types
invalid_relationships = set(
    final_relationships_with_ids["relationship_type"]
) - allowed_relationships

print("Invalid relationship types:", invalid_relationships)

# Check for missing IDs
print(
    "Missing source IDs:",
    final_relationships_with_ids["source_id"].isna().sum()
)

print(
    "Missing target IDs:",
    final_relationships_with_ids["target_id"].isna().sum()
)

# Final relationship counts
print("\nRelationship counts:")
print(
    final_relationships_with_ids["relationship_type"]
    .value_counts()
)

print("\nTotal relationships:",
      len(final_relationships_with_ids))

Invalid relationship types: set()
Missing source IDs: 0
Missing target IDs: 0

Relationship counts:
relationship_type
ASSOCIATED_WITH    54
USED               39
OWNS               18
CALLED             12
Name: count, dtype: int64

Total relationships: 123

In [46]:
# Export final NLP outputs

final_entities_df.to_csv("nlp_entities.csv", index=False)
final_relationships_with_ids.to_csv("nlp_relationships.csv", index=False)

print("Export completed!")
print("nlp_entities.csv:", len(final_entities_df), "entities")
print("nlp_relationships.csv:", len(final_relationships_with_ids), "relationships")

Export completed!
nlp_entities.csv: 81 entities
nlp_relationships.csv: 123 relationships